### ISSUE TITLE
Rust 1.0.0-beta.2 is out

### ISSUE THREAD

**Issue by himikof** [Heather/gentoo-rust#107]
See the announcement: http://users.rust-lang.org/t/psa-1-0-0-beta-2-is-out/1019.
Upstream expects to release incremental beta channel updates once per week.

I'm reporting this issue to make sure it (and subsequent updates) will not be missed, as there is not as much publicity on them as on the first beta release.

**Comment by jauhien** [comment]
Thanks for information.

dev-lang/rust-bin done. dev-lang/rust waits until tomorrow.
