### ISSUE TITLE
New SLOTs schema

### ISSUE THREAD

**Issue by jauhien** [Heather/gentoo-rust#115]
I think we need to finally decide on what SLOTs we need to have.

1. We need SLOTs that match upstream release channels

2. I would like to introduce SLOTs for `dev-lang/rust-bin` (corresponding to release channels), but there is a problem here: bundled cargo. I can add its symlink to the list of symlinks managed by eselect, but then if user switches to `dev-lang/rust`, he looses his cargo. May be this is not a big issue, as such user can use normal cargo, not bundled one, but if there is some good solution, I would like to find it.

**Comment by jauhien** [comment]
Well, slots for rust-bin were added: 1.0 and nightly.

Now I would like to discuss new SLOTs schema. my proposition is like this: we use the same slots as upstream release channels, i.e. `stable`, `beta` and `nightly`. Changes for now are `1.0 -> stable` and introduction of `beta` SLOT.

If no complain I will proceed with these changes during this week (may be at the weekend).

**Comment by omasanori** [comment]
Looks good to me.

**Comment by Heather** [comment]
I don't have anything against it either
