### ISSUE TITLE
Check system-llvm USE

### ISSUE THREAD

**Issue by jauhien** [Heather/gentoo-rust#122]
See https://bugs.gentoo.org/show_bug.cgi?id=546704

Please, somebody check if rust builds with system LLVM, as I have no possibility to check it now.

Also, @Heather, what is your right email, so I can fix metadata?

**Comment by Heather** [comment]
@jauhien heather (at) live.ru and gentoo one is cynede (at) gentoo.org

**Comment by vberger** [comment]
I've been overriding this flag and using my system LLVM for some time, and never had any problem.
I'm running with `sys-devel/llvm-3.6.0` and `dev-lang/rust-9999` on a x86_64 gentoo installation.

**Comment by jauhien** [comment]
@vberger: thanks, then I'm unmasking it

@Heather: ok, I'll fix metadata then

**Comment by jauhien** [comment]
Fixed.
