### ISSUE TITLE
dev-rust/cargo-0.3.0 fails to emerge

### ISSUE THREAD

**Issue by zetok** [Heather/gentoo-rust#142]
Reproducible: Always

``build.log`` & ``emerge --info``: https://gist.github.com/zetok/333ace03c8e11be1d5ec

**Comment by Heather** [comment]
@zetok may you try to build with rust `1.1.0` and if it will help then we will correct dependencies there

**Comment by zetok** [comment]
@Heather I already have rust `1.1.0` installed

**Comment by Heather** [comment]
@zetok very strange then https://gist.github.com/zetok/333ace03c8e11be1d5ec#file-build-log-L108

**Comment by zetok** [comment]
huh, weird:
```
[U] dev-lang/rust-bin
     Available versions:  
     (stable) (~)1.0.0 (~)1.0.0[3] (~)1.1.0[3]
     (beta) **99[3]
     (nightly) **999[3]
       {cargo-bundled doc}
     Installed versions:  1.0.0(stable)[3](13:53:51 24.05.2015) 1.1.0(stable)[3](16:31:30 05.07.2015)
     Homepage:            http://www.rust-lang.org/
     Description:         Systems programming language from Mozilla
```

**Comment by Heather** [comment]
ah... you've got both... try to use eselect-rust

**Comment by jauhien** [comment]
@zetok: you have old rust 1.0.0 that has 1.0 SLOT. eix is bad on showing such cases. Please, unmerge rust-1.0.0 and recheck.

**Comment by zetok** [comment]
with selected `rust-1.1.0` emerged successfully

**Comment by jauhien** [comment]
Ah, moment, we need to upgrade cargo dependencies, @gentoo90.

**Comment by gentoo90** [comment]
Now it's
```ebuild
DEPEND="${COMMON_DEPEND}
	|| ( >=dev-lang/rust-1.1.0 >=dev-lang/rust-bin-1.1.0 )
	dev-util/cmake"
```
What should it be?

**Comment by jauhien** [comment]
ah, it already is ok, thanks @gentoo90, closing then.

**Comment by Heather** [comment]
it's not in repository yet...
