### ISSUE TITLE
virtual/cargo is necessary for proper handling of rust-bin[cargo-bundled]

### ISSUE THREAD

**Issue by albel727** [Heather/gentoo-rust#145]
The fact that packages like racer and SolidOak depend on dev-rust/cargo directly instead of an appropriate virtual/cargo is the source of constant pain on my system. I don't want to build rust and cargo from source, and dev-util/cargo often fails to build with whatever rust-bin I have at the time anyway, so the natural choice is rust-bin with cargo-bundled use flag. 

But of course, rust-bin[cargo-bundled] blocks dev-rust/cargo, which everything else tends to directly depend on. And what's worse, there are things directly depending on dev-lang/rust instead of virtual/rust too, completely disregarding that I have rust-bin already! All of this forces me to manually fix the dependencies after every sync. 

I suggest ensuring the following minimal sanity conditions:

1. Things that depend on dev-lang/rust should properly depend on virtual/rust instead (yes, racer, SolidOak and rusty-tags, I'm looking at you).
2. virtual/cargo should be introduced with dependencies like `|| ( dev-rust/cargo dev-lang/rust-bin[cargo-bundled] )`
3. Things that depend on dev-rust/cargo should properly depend on virtual/cargo instead (racer, SolidOak, rust-bindgen)

**Comment by jauhien** [comment]
I'm going to split out cargo-bin, see this issue: https://github.com/gentoo/gentoo-rust/issues/4
