### ISSUE TITLE
dev-lang/rust in the main Gentoo tree

### ISSUE THREAD

**Issue by jauhien** [Heather/gentoo-rust#24]
Let's discuss the future of Rust in Gentoo here.

**Comment by jauhien** [comment]
All live ebuilds were removed from the tree. From now the latest live Rust will be available only from this overlay. I will add versioned ebuilds to the tree along with coming of new versions and their stabilization.

**Comment by Heather** [comment]
@jauhien sounds good

**Comment by jauhien** [comment]
@Heather: probably no, any specific thing can be addressed by separate issue. Closing this.
