### ISSUE TITLE
Support for Cargo

### ISSUE THREAD

**Issue by jauhien** [Heather/gentoo-rust#25]
There are two points we need to address with cargo:

- cargo ebuild itself: it does fetching during compile time. It is bad even for live-ebuilds, so ebuild should be fixed somehow to do every fetching in src_unpack

- general support for cargo: as far as I understand it is itself some kind of package manager, so we'd like to have a mechanism for it that allows it to use system-wide installed packages (if it does not use them already, just fetching everything it needs, eclass will be probably needed here), and may be other mechanism that allows to automatically generate ebuilds (like the stuff that I've written for elisp elpa and pypi before)

I'm completely new in cargo so I need to figure out how does it really work and how to support it in the correct way.

**Comment by p8952** [comment]
Admittedly I've only briefly worked with rust and glanced over the ebuilds here and in the tree. But +1 to what @anthonyryan1 said.

Cargo seems to act as both a build system in the style of make coupled with a package manager in the style of gem or pip.

The first part appears to be critical for anyone using rust as `cargo build` is the way you compile a project. Having rust in the tree without it is not much use.

The second part seems less important. While at some point an eclass will be needed this will only be for packaging end user applications and their dependencies. Given rust's alpha state I don't see this being needed for some time.

**Comment by jauhien** [comment]
Continued in https://github.com/gentoo/gentoo-rust/issues/4
