### ISSUE TITLE
dev-lang/rust-1.7 is not in virtual/rust

### ISSUE THREAD

**Issue by trofi** [Heather/gentoo-rust#33]
Today's update does not pull rust-1.7 as:

```
dev-lang/rust:stable

  (dev-lang/rust-1.7.0:stable/stable::rust, ebuild scheduled for merge) conflicts with
    =dev-lang/rust-1.6.0* required by (virtual/rust-1.6.0:0/0::rust, installed)
    ^
```

**Comment by Heather** [comment]
@trofi please use https://github.com/gentoo/gentoo-rust

**Comment by Heather** [comment]
added https://github.com/gentoo/gentoo-rust/commit/74b32c6e9510999bac15d604037f0a8950641cb3

**Comment by trofi** [comment]
It appears I already used it :) Picked wrong fork, sorry.

Works now. Thank you!
