### ISSUE TITLE
Cargo fails to fetch external dependencies

### ISSUE THREAD

**Issue by omasanori** [Heather/gentoo-rust#42]
Error message:
> task '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.', /var/tmp/portage/dev-lang/rust-9999-r3/work/rust-9999/src/libcore/result.rs:744

Probably requiring `net-misc/curl` with proper USE flags fixes this.

**Comment by Heather** [comment]
@omasanori maybe curl should be added to DEPS?

**Comment by oleid** [comment]
I was affected, too. I rebuilt my libcurl with +metalink +rtmp +curl_ssl_openssl -curl_ssl_nss and it works now. I'm not sure if the switch from nss to openssl was nessecary - my guess would be metalink, but I didn't try, yet.

**Comment by redneb** [comment]
> I was affected, too. I rebuilt my libcurl with +curl_ssl_openssl -curl_ssl_nss and it works now.

Yes, it appears that the `curl` crate depends on openssl for tls support: https://github.com/carllerche/curl-rust/blob/master/Cargo.toml.
