### ISSUE TITLE
Rust 1.0.0 alpha is out

### ISSUE THREAD

**Issue by Heather** [Heather/gentoo-rust#50]

**Comment by geovex** [comment]
I can't build it from official sources. This is wired.
```
/home/tormoz/rustc-1.0.0-alpha/src/libcore/str/mod.rs:1620:10: 1620:11 error: expected `fn`, found `}`
/home/tormoz/rustc-1.0.0-alpha/src/libcore/str/mod.rs:1620 #[stable]}
                                                                    ^
```

**Comment by geovex** [comment]
You may look at https://github.com/geovex/gentoo-rust/blob/rust_1.0/dev-lang/rust/rust-1.0.0_alpha.ebuild
The problem is i can't build it like 0.12 with --enable-local-rust and it fetches some things while build.
