### ISSUE TITLE
multiple concerns about packaging

### ISSUE THREAD

**Issue by williamh** [Heather/gentoo-rust#52]
Hi all,

I have just become a co-maintainer of rust and I have some concerns about the packaging.

this is upstream's release plan for Rust [1]. In a nutshell, that means there will be three release channels -- nightlys, betas and stable releases. This means features will go from nightlys to a beta then to a stable release. I was told by stevekladnik on the #rust irc channel that users should only be using the nightlys at this time until the beta is released. Because of this recommendation, I think we should get rid of all 0.x versions of Rust.

Gentoo bug 534372 [2] was filed because the nightly ebuild in the tree is now unable to download the sources. One of the bug wranglers voiced concerns about us using our own constructed src_uri and using wget inside the src_unpack function to download the tarball. He is correct; we shouldn't be doing this.

Fortunately, stevekladnik told me that we can find the commit hash for the commit used for the snapshot in src/snapshots.txt on the S line.

The git-r3 eclass supports pinning to a specific commit with the EGIT_COMMIT variable, so I think the nightly ebuild can be a literal live ebuild, with the version number 999, then we would have to set the EGIT_COMMIT variable manually to match the latest snapshot.

Also, the nightly binary ebuild needs to be fixed to not use wget. We may still be able to treat it as a live ebuild; I will look into that. If not, I suggest dropping all rust*bin ebuilds until we actually have releases to work with.

Another thing I saw is the revision numbers on live ebuilds; this is unnecessary. I propose that we downgrade all of the live ebuilds to plain version numbers.

Here's the short version of everything I said:

- I think we should remove all 0.x versions of rust.
- Live ebuilds should have version numbers with no revisions.
- wget should not be used in src_unpack to download a tarball; portage handles that.

- This is low-hanging fruit for me, but also based on [1], I'm not sure that we should be slotting rust., since stable versions will be backward compatible with older stable versions.

I am willing to work on these changes, so let me know what your thoughts are.

Thanks much,

William

[1] https://github.com/rust-lang/rfcs/blob/master/text/0507-release-channels.md
[2] https://bugs.gentoo.org/show_bug.cgi?id=534372

**Comment by Proksima** [comment]
+1

**Comment by Heather** [comment]
@williamh I think we can add `~` keywords to nightly builds but removing most recent release version is not the way for sure.

**Comment by williamh** [comment]
@Heather:
The web site recommends using the nightly builds [1]. The 0.12 release is nothing more than an old snapshot at this point. Also, I specifically asked on the IRC channel and was told that users should be using the nightly builds.

The only way the nightly build can have ~keywords added is if you have a separate tarball that goes with each ebuild. Since upstream provides one nightly tarball that never changes names, this is not possible unless we mirror the tarballs somewhere, which would be a lot of work.

[1] http://www.rust-lang.org

**Comment by o01eg** [comment]
@Heather:
As I remember `~` uses for betas and not tested releases. Live ebuilds should have `**` keywords.

**Comment by Heather** [comment]
@williamh I don't like this solution. Nightly means 999 or 9999, it means you should rebuild it every day or use binary nightly. It doesn't means that you should start versioning them like you suggest. Nightly is recommended and that's why we have 999 and 9999 but however there is no sane point to remove stable releases and change versioning system.

**Comment by williamh** [comment]
@o01eg:
Not "**" keywords, but no keywords at all. the KEYWORDS variable can either be "" or not mentioned at all.

@Heather:
I think you misunderstood me. I wasn't advocating mirroring the tarballs, Iwas just explaining that we would need to if we wanted to move the nightly ebuilds to ~keywords.

**Comment by Heather** [comment]
@williamh maybe then how do you plan to use `EGIT_COMMIT`

**Comment by Heather** [comment]
@williamh ahm yes, maybe I did :) If you want to change `999` to commit from `src/snapshots.txt` I think it's fine solution. Personally I don't think that it's big improvement but it's not bad either.

**Comment by williamh** [comment]
@Heather:
It looks like the nightly tarballs do not correspond to the snapshots listed in snapshots.txt. I think those might be the stage 0 snapshots, so I can't make the nightly pull from git.

I asked around on #gentoo-dev, and was told that if we want the nightly ebuilds in  the main tree the preferred way to do that would be to mirror the tarballs since upstream doesn't appear to make a separate tarball for each nightly. 

But, someone did make another suggestion that I'll look at, using the -> operator in src_uri. I'll update you here once I know if that will work.

**Comment by Heather** [comment]
@williamh not sure how `->` will help here.

What do you think about:
 - make something alike `dev-lang/rust-nightly`
 - mirror nightly tarball every month or more often...
 - name them alike `rust-nightly-2015.05.15`

it will not break `rust` versioning and will not change logics of current `999` ebuilds

**Comment by williamh** [comment]
After much thinking about this, I have come up with something that I think you will like better.

We currently offer packages for "rust" and "rust-bin", and we use slots for a release version, a nightly version and git.

I propose that we offer four packages instead:

- rust would be the standard package. This would be released versions and a live ebuild.

- rust-bin would install the upstream binary releases. There would be no live ebuild here.

- rust-nightly would build from the nightly source tarball. This could stay live.

- rust-nightly-bin would install the upstream nightly binary build. This could also stay live.

This would do several things for us:

- It would bring our packaging in line with what upstream offers.

- We could get rid of slots since you wouldn't need more than one of these four packages installed at   the same time. We could set up blockers to control the installation.

- We would not have to mirror nightlys unless we decided we wanted to specifically make one of them ~arch then maybe stabilize it for some reason. If we did that, we could just mirror that nightly.

I'll do all the work for this, just let me know what you think about the idea.

**Comment by Heather** [comment]
@williamh yes, this sounds good for me. ( also will be glad to hear opinions from @omasanori @jauhien )

**Comment by omasanori** [comment]
Probably I'll be happy with suggested changes but I doubt that "We could get rid of slots ..." means "if you installed one of them then you can't install other three nor other version of same package without uninstalling it."
I've checked compilers' behaviors between versions and built-from-source vs. binary distribution, so I'm worrying if I need to uninstall 1.1 before testing 1.0 and rebuild from source again and again to compare with binary distributions.

**Comment by Heather** [comment]
@omasanori I never used to install two versions of rust in the same time but seems like it's useful for some people.
Thanks @jauhien for https://github.com/jauhien/eselect-rust so we can easily pick switch between, seems like.
@williamh what do you think?

**Comment by jauhien** [comment]
What is the reason of splitting nightly version to a different package? How is it different from the live version? Nightly never should go to ~, so why wget is worse than git? )

The only real problem with nightly that I see is the lack of checking of checksums (git does some checking). That's bad, but afaik upstream anyway does not provide checksums for tarballs. Am I missing any points here?

I would suggest to stay with the packaging schema that we have currently. I will think tree with overlay in the nearest time and also will look if something needs to be fixed for overlay.

In the future I would concider these slots for rust:

* versioned slots
* alpha
* beta
* git

Depending on nightly being actual, nightly slot as well.

**Comment by williamh** [comment]
@jauhien:
Since others on the team want to keep slots, I will support slots as well. I recommend slot="${PV}", slot="nightly" and slot="live". That would cover alphas/betas for you by creating separate slots for them. I'll do that in my next pull request.

I was thinking we should follow upstream's lead and change our packaging schema, but my thoughts are changing. I was thinking that as a user I would have to type something like, "emerge =rust-999" and know that was the nightly version, but I recall now that you can type: "emerge rust:nightly" and get the same thing right? If that's true, I won't push for splitting out nightly and nightly-bin to separate packages.

**Comment by jauhien** [comment]
@williamh: ok. Then the only really bad thing we have now is not checking checksums for nightly tarball (and not checking checksums for stage0 downloaded for git, or is it checked?). We should think how to fix it.

**Comment by omasanori** [comment]
@williamh thank you.

@jauhien checksums for stage0 tarballs [is checked](https://github.com/rust-lang/rust/blob/master/src/etc/get-snapshot.py#L68) after downloading.

**Comment by williamh** [comment]
@jauhien:
Since upstream doesn't name the nightly tarball differently every time they build it, the only way for us to checksum it would be to mirror it somewhere. The more I think about it, if we are going to keep the nightlys live, I'm not that concerned about checksums since we do not do this kind of checking with other live ebuilds.

The more I think about our use of slots, I'm still not quite settled with it, but I am willing to open a separate issue/pull request to discuss my thoughts.
