### ISSUE TITLE
dev-rust/cargo fails to build on x86; tries to use 64-bit rust nightly

### ISSUE THREAD

**Issue by strout** [Heather/gentoo-rust#61]
The script `.travis.install.deps.sh` run during `src_prepare` appears to use an environment variable `BITS` to distinguish between x86 and x86_64. When the variable is unset, it tries to use use the x86_64 nightly, which fails on an x86 system.

The relevant excerpt from the output of `emerge =dev-rust/cargo-9999-r1`:

    + '[' '' = 32 ']'
    + src=i686
    + dst=x86_64
    + cp -r rust-nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu rust-nightly-x86_64
    -unknown-linux-gnu/lib/rustlib
    + cd rust-nightly-x86_64-unknown-linux-gnu
    + find lib/rustlib/i686-unknown-linux-gnu/lib -type f
    + sed 's/^/file:/'
    + ./rust-nightly-x86_64-unknown-linux-gnu/install.sh --prefix=rustc
    install: looking for install programs
    install:
    install: found mkdir
    install: found printf
    install: found cut
    install: found grep
    install: found uname
    install: found tr
    install: found sed
    install: found chmod
    install:
    install: processing ./rust-nightly-x86_64-unknown-linux-gnu/install.sh args
    install:
    install: CFG_DESTDIR          :=
    install: CFG_PREFIX           := rustc
    install: CFG_LIBDIR           := rustc/lib
    install: CFG_MANDIR           := rustc/share/man
    install:
    install: validating ./rust-nightly-x86_64-unknown-linux-gnu/install.sh args
    install:
    install: verifying platform can run binaries
    install: error: can't execute binaries on this platform

Changing the `src_prepare` line to `CFG_DISABLE_LDCONFIG="true" BITS="32" ./.travis.install.deps.sh` in the work directory succeeds. (I'd submit a pull request but I don't know the proper way to conditionally set it for 32/64 bit.)

**Comment by Heather** [comment]
you can try `x86?` alike here: http://devmanual.gentoo.org/ebuild-writing/variables/index.html#src_uri
