### ISSUE TITLE
app-vim/rust-mode failed to build

### ISSUE THREAD

**Issue by nutsi** [Heather/gentoo-rust#66]
I think, this comment is for here:

> >>> Source unpacked in /var/tmp/portage/app-vim/rust-mode-9999/work
> * ERROR: app-vim/rust-mode-9999::rust failed (prepare phase):
> *   The source directory '/var/tmp/portage/app-vim/rust-mode-9999/work/rust-mode-9999
> /src/etc/vim' doesn't exist
>  * 
 > * Call stack:
 > *            ebuild.sh, line 746:  Called __ebuild_main 'prepare'
 > *   phase-functions.sh, line 964:  Called __dyn_prepare
 > *   phase-functions.sh, line 369:  Called die
 > * The specific snippet of code:
 > *   		die "The source directory '${S}' doesn't exist"
 > * 
 > * If you need support, post the output of `emerge --info '=app-vim/rust-mode-9999::rust'`,
 > * the complete build log and the output of `emerge -pqv '=app-vim/rust-mode-9999::rust'`.
 > * The complete build log is located at '/var/tmp/portage/app-vim/rust-mode-9999/temp/build.log'.
 > * The ebuild environment file is located at '/var/tmp/portage/app-vim/rust-mode-9999/temp/environment'.
 > * Working directory: '/usr/lib64/python3.3/site-packages'
 > * S: '/var/tmp/portage/app-vim/rust-mode-9999/work/rust-mode-9999/src/etc/vim'
> >>> Failed to emerge app-vim/rust-mode-9999, Log file:
>
> >>>  '/var/tmp/portage/app-vim/rust-mode-9999/temp/build.log'
>
 > * Messages for package app-vim/rust-mode-9999:
>
 > * ERROR: app-vim/rust-mode-9999::rust failed (prepare phase):
 > *   The source directory '/var/tmp/portage/app-vim/rust-mode-9999/work/rust-mode-9999> /src/etc/vim' doesn't exist
 > * 
 > * Call stack:
 > *            ebuild.sh, line 746:  Called __ebuild_main 'prepare'
 > *   phase-functions.sh, line 964:  Called __dyn_prepare
 > *   phase-functions.sh, line 369:  Called die
 > * The specific snippet of code:
 > *   		die "The source directory '${S}' doesn't exist"
 > * 
 > * If you need support, post the output of `emerge --info '=app-vim/rust-mode-9999::rust'`,
 > * the complete build log and the output of `emerge -pqv '=app-vim/rust-mode-9999::rust'`.
 > * The complete build log is located at '/var/tmp/portage/app-vim/rust-mode-9999/temp/build.log'.
 > * The ebuild environment file is located at '/var/tmp/portage/app-vim/rust-mode-9999/temp/environment'.
 > * Working directory: '/usr/lib64/python3.3/site-packages'
 > * S: '/var/tmp/portage/app-vim/rust-mode-9999/work/rust-mode-9999/src/etc/vim'

I don't really have the time to inspect what is happening with that, but if someone has no idea which would help.

Thanks,

**Comment by omasanori** [comment]
@nutsi Please update the overlay (e.g. `layman -s rust`) and try to install 9999-r1.

**Comment by Heather** [comment]
I close it for now. Please reopen if @omasanori suggestion will not help.

**Comment by nutsi** [comment]
after ```layman -s rust``` errors still the same.

**Comment by williamh** [comment]
Once my pull request #68 is merged this should not be an issue.

**Comment by jauhien** [comment]
Works for me, issue probably should be closed.
