### ISSUE TITLE
app-admin/eselect-rust - rust-lldb symlink setting failed

### ISSUE THREAD

**Issue by omasanori** [Heather/gentoo-rust#69]
Recent Rust provides rust-gdb instead of rust-lldb, so you may see a "rust-lldb symlink setting failed" warning when you switched its version with `eselect rust set`.
Required changes are already pull-requested upstream by some developers. (Thanks!) This issue will be closed when the new version of eselect-rust is released.

**Comment by jauhien** [comment]
Yes, I have a pull request for it, I'll fix it asap.

**Comment by omasanori** [comment]
Thank you! Please take your time. :smiley:

**Comment by jauhien** [comment]
I have merge support for gdb. It still will result in warning for lldb, I will remove this later when I will clean up the tree.

**Comment by jauhien** [comment]
Fixed.
