### ISSUE TITLE
rust-mode and rust-zshcomp: stop blocking latest dev-lang/rust

### ISSUE THREAD

**Issue by omasanori** [Heather/gentoo-rust#72]
After removing revision `-rN` from the version of packages, `app-emacs/rust-mode`, `app-vim/rust-mode` and `app-shells/rust-zshcomp` blocks `dev-lang/rust-9999`, `-999`, etc.

Probably updating `DEPEND` of the ebuilds will fix this problem.

**Comment by jauhien** [comment]
Fixed by #73. We need these blockers no longer.
