### ISSUE TITLE
Strange placement of gdb_rust_pretty_printing.py

### ISSUE THREAD

**Issue by o01eg** [Heather/gentoo-rust#91]
When I using rust-gdb I get warning:
```
Warning: /usr/lib/rustlib/etc: No such file or directory.
```

I found out that here installs files `gdb_rust_pretty_printing.py` and `lldb_rust_formatters.py` but when I look up for first it happens to other location:
```
/usr/lib64/rust-9999/rustlib/etc/gdb_rust_pretty_printing.py
```
Should this file be installed into `/usr/lib/rustlib/etc`?

**Comment by jauhien** [comment]
No, it should not. We need to fix `gdb_rust_pretty_printing.py` instead.

Thanks for reporting.

**Comment by jauhien** [comment]
https://github.com/gentoo/gentoo-rust/issues/7
