### ISSUE TITLE
rust 1.0.0 beta is out

### ISSUE THREAD

**Issue by williamh** [Heather/gentoo-rust#95]
Hi all, I just saw a tweet about rust 1.0. beta being out.
I would like to go to the irc channel for upstream and find out if they have multiple channel installation support working yet before we write the ebuild.
If they don't, I think we shouldn't try to support slots downstream at this point.
What do others think?

**Comment by Heather** [comment]
@williamh current implementation is done here: https://github.com/Heather/gentoo-rust/pull/96

I like that we already have it. Not sure if slots is related to the beta release?

**Comment by himikof** [comment]
The ebuild from #96 is missing `--release-channel beta` flag to configure script, so the resulting rustc is actually "dev rustc built from beta sources", the main difference being unstable features being enabled.
`rustc --version` output after merging: `rustc 1.0.0-dev (built 2015-04-04)`. It should be `rustc 1.0.0-beta`.

**Comment by Heather** [comment]
@himikof should be fine now
